### ISSUE TITLE
Currently not available under Ubuntu 14.04 64-bit

### ISSUE THREAD

**Issue by chbi** [opscode-cookbooks/chef-server#48]
Currently chef-server is not installable with this cookbook on Ubuntu 14.04 64-bit. It fails with "Could not locate chef-server package matching version 'latest' for node."

I'd fix the error myself but I don't know enough about ruby and chef ... could anybody be so kind and fix this?

**Comment by BarthV** [comment]
Still blocking for me.
Any update for this issue ?

**Comment by jtimberman** [comment]
We only release platform-version-specific packages for the platform versions that we test on. At this time we're not building new packages for Chef Server 11 except for security issues and bug fixes. The packages are built on Ubuntu 10.04, and may work fine on 14.04. We strongly encourage users to upgrade to Chef Server 12, as that has packages that are tested against 14.04, and we have the packages hosted on Package Cloud.

We'll have more information about Chef Server 12 and this cookbook soon. And by soon, I mean I'm writing up information about this for the mailing list later today (Friday 2/20).
