### ISSUE TITLE
Workflow for chef-server cookbook?

### ISSUE THREAD

**Issue by miketheman** [opscode-cookbooks/chef-server#49]
I believe this cookbook is basically meant to help with running and maintaining an omnibus-based Chef Server - and run the underlying cookbook located here: https://github.com/opscode/omnibus-chef-server

That repo doesn't have an Issues set up yet, so I;m uncertain as to where to discuss proposed changes to add/change functionality to that cookbook, since this one seems to only pass along an open-ended Hash of configuration options.

**Comment by jtimberman** [comment]
Closing this as we're now using https://github.com/chef/chef-server/issues or https://github.com/chef/opscode-omnibus/issues w/ Chef Server 12.
