### ISSUE TITLE
Stop using deprecated download-server url

### ISSUE THREAD

**Issue by lamont-granquist** [opscode-cookbooks/chef-server#52]
The download server URL has been deprecated for a long time:

https://github.com/opscode/opscode-omnitruck#deprecated-urls

The cookbook should at least use the metadata URL correctly to download the metadata and parse the s3 url out of it, e.g.:

```
https://www.opscode.com/chef/metadata-server?v=&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
```

**Comment by jtimberman** [comment]
Closing. I'm going to have more information posted to the mailing list about this later today (Friday 2/20). TL;DR in a Chef Server 12 world we use Package Cloud for packages, as package installation is much easier to automate with repositories, than using the Omnitruck API or the install.sh script.
