### ISSUE TITLE
Add ability to install chef12

### ISSUE THREAD

**Issue by jperry** [opscode-cookbooks/chef-server#59]

**Comment by BarthV** [comment]
After reading the template i saw that node['chef-server']['configuration'] already expose chef-server.rb conf.

So it's ok for me

**Comment by jtimberman** [comment]
I'm going to have more information posted to the mailing list about this later today (Friday 2/20). Stay tuned.

**Comment by rastasheep** [comment]
For historical purposes, @jtimberman's thread on mailing list can be found here:
http://lists.opscode.com/sympa/arc/chef/2015-02/msg00351.html

**Comment by jtimberman** [comment]
https://github.com/opscode-cookbooks/chef-server/pull/71

This PR moves the cookbook to supporting only Chef Server 12 with the default recipe, as described in the mailing list post linked above.
