### ISSUE TITLE
Feature request: log rotation

### ISSUE THREAD

**Issue by pburkholder** [opscode-cookbooks/chef-server#63]
I've been asked about this and it seems reasonable to include log rotation in this cookbook. Or, since there are so many logs, maybe a 'chef-server-ctl rotate-logs' command.

**Comment by obazoud** [comment]
+1

**Comment by GolubevV** [comment]
+1

**Comment by jtimberman** [comment]
I think this shouldn't be handled by this cookbook, it should be handled by `chef-server-ctl`. Then users who wish to make use of such a thing can have a cookbook that does it in the way that makes most sense for their infrastructure, be that a cron job.

Please open an issue in https://github.com/chef/chef-server/issues.
