### ISSUE TITLE
Option to disable automatic upgrading

### ISSUE THREAD

**Issue by docwhat** [opscode-cookbooks/chef-server#66]
I like most of this cookbook, but I don't want it upgrade or downgrade the chef-server once installed.  The rest (managing the config, etc.) is handy on its own.  The installation part is useful for first-time installs.

Something like an option for "install_if_missing" would be handy.

**Comment by jtimberman** [comment]
So, in PR #71, we support Chef Server 12, which is done through using the Package Cloud repository where we publish packages. Older versions should be available there, so you can pin the version you want with the `node['chef-server']['version']` attribute.
