### ISSUE TITLE
More maintainer

### ISSUE THREAD

**Issue by PierreRambaud** [opscode-cookbooks/chef-server#67]
Hi,
It seems this repository isn't up to date. For my purpose, I try to install a chef-server in a heat stack, but `http://www.opscode.com` is not a valid uri and omnitruck raise an exception. 
I checked issues and pull requests and it looks like I'm not alone in this situation.
Please can you do some reviews on PR, or add someone you trust to do it.

Regards

**Comment by jtimberman** [comment]
Hello,

We've taken steps to address the incompatibility with Chef Server 12. We'll ensure that this cookbook is updated for future versions of the server, accordingly. 

More information is available in this mailing list thread:

http://lists.opscode.com/sympa/arc/chef/2015-02/msg00351.html

Cheers,
Joshua

**Comment by PierreRambaud** [comment]
Thanks ;)
